### ISSUE TITLE
Premium příkazy

### ISSUE THREAD

**Issue by Trox-cz** [mc-diamondcrew-cz/issue-tracker#15]
/rain se v chatu objeví Čas byl úspěšně nastaven na noc
/sun nefunguje změna na den, do chatu napíše ''Čas byl uspěšně nastaven na noc,,

/f fly - nefunguje
/settings - nelze vypnout vylepšené kácení stromů,nad glowstonem je nápis nelze detekovat a při kliknutí mi to v chatu oznámí že na to nemám pravomoci

**Comment by ThePlay3r** [comment]
- /sun Nastavuje pocasi na slunecno, nikoli den.
- /f fly nema fungovat.
- /settings opraveno 🔧
