### ISSUE TITLE
Lands

### ISSUE THREAD

**Issue by Trox-cz** [mc-diamondcrew-cz/issue-tracker#16]
V nastevní Zemně nemohu nic vypnout ale ani zapnout např. spawn monster,zvířat apod - oznamuje mi to že nemám na to pravomoce
![2021-03-20_12 02 16](https://user-images.githubusercontent.com/80423233/111867427-23840b80-8974-11eb-95c9-bb5b45c40551.png)

**Comment by ThePlay3r** [comment]
Opraveno. 🔧
