### ISSUE TITLE
Problém s připojením

### ISSUE THREAD

**Issue by R3kwy** [mc-diamondcrew-cz/issue-tracker#22]
Když se snažím napojit píšr mi to AntiVPN Před připojením deaktivujte VPN, prosím, ale já žádnou VPN zaplou nemám. Asi je to technická chyba nebo nevím. Herní nick: Daiwert

**Comment by ThePlay3r** [comment]
Chyba s dynamickou IP, restartování počítače většinou problém vyřeší, povolené IP jsou pouze z CZ/SK.
