### ISSUE TITLE
Nápad na jeden datapeck

### ISSUE THREAD

**Issue by JIndraRed** [mc-diamondcrew-cz/issue-tracker#35]
https://www.youtube.com/watch?v=UCUivDpVDhE

**Comment by ThePlay3r** [comment]
Podle mého názoru příliš 'OP' mechanika, aktuálně je Vám elytra umožňuje létat, což je samo o sobě poměrně dost silná funkce, ovšem za cenu ztráty nejsilnějšího kousku sady brnění, takže je to létání za trochu armor.
Přidáním tohoto datapacku by elytra neměla žádné podobné nevýhody a představovala by šíleně silný předmět.

Nechám prostor na vyjádření i pro ostatní členy komunity, ale nemyslím si, že přidávání podobných funkcí je dobrý nápad.

**Comment by R3kwy** [comment]
Za mě je to aktuálně v pořádku. Podle mě, kdyby se tohle přidalo ta ztrácí smysl nosit chestplate. Všichni by létali v pvp jak mouchy a celý pvp systém by šel na dračku. Nemyslím si, že by to jakkoliv zlepšilo hru, ba naopak, jelikož Elytry jsou už takle dost silné. No a také by to moc nepomohlo, protože si osobně myslím, že by se nedokázali spojit datapackem přidané enchanty s tímhle datapackem, tudíž by se to ku mému ani nevyplatilo. Ale tohle je pouze můj názor, třeba někdo jiný bude mít jiný.

**Comment by ThePlay3r** [comment]
Prvek se na server pridavat nebude.
