### ISSUE TITLE
X-ray

### ISSUE THREAD

**Issue by CreeperM4n438** [mc-diamondcrew-cz/issue-tracker#38]
Zdravím 
Vyzkoušel jsem dnes na serveru xray a myslím si že by bylo dobré přidat nějakou ochranu nerad bych aby někdo podváděl. Nevím zda funguje v klasickém světě a však v netheru se s ním dá vše vidět. Rád bych se také omluvil za použití a však nemám z toho žádný osobní zisk pouze jsem toto chtěl vyzkoušet.

**Comment by ThePlay3r** [comment]
Duplicate of #31
