### ISSUE TITLE
Létání bez enchantu #2

### ISSUE THREAD

**Issue by Bugg3rofficial** [mc-diamondcrew-cz/issue-tracker#39]
Jak tady psal R3kwy že po tom co si sundá boty s enchantem křídla tak furt litá, já lítám i když vůbec nemám enchant křídla.... Dneska se mi jen tak nějak podařilo že můžu létat ve svojí resce, Trox viděl můj Armor takže viděl že nemám enchant na létání. 
Nevím jak se mi to podařilo ale po odpojení se to létání hned zruší.

**Comment by ThePlay3r** [comment]
Duplicate of #37
