### ISSUE TITLE
Airdrope chyba

### ISSUE THREAD

**Issue by Mofieu** [mc-diamondcrew-cz/issue-tracker#8]
Byl jsem na airdropu a při otevření beden z kterých mě padli peníze mě peníze nepadli, nikde je nemám, ani v bance
![dddddddddd](https://user-images.githubusercontent.com/80292273/111000546-84af4c00-8382-11eb-99c8-716723c20d86.PNG)
![dddd](https://user-images.githubusercontent.com/80292273/111000561-8a0c9680-8382-11eb-85e1-628ee698cb62.PNG)
![ddddd](https://user-images.githubusercontent.com/80292273/111000579-8f69e100-8382-11eb-8899-c08e6e3bcdcf.PNG)

**Comment by ThePlay3r** [comment]
Plugin je ve vychozim nastaveni, odmeny budou tedy kompletne jine.
